overrides:
    config_overrides:
            techs:
                solar_thermal_collector.exists: false  # TODO: create ST timeseries to allow these techs to exist
                solar_thermal_energy.exists: false  # TODO: create ST timeseries to allow these techs to exist
                ashp.exists: false
                gshp.exists: false
                demand_space_heat.exists: false
                demand_water_heat.exists: false
                ashp_heat_storage_small.exists: false
                ashp_tech_heat_to_demand.exists: false
                gshp_heat_storage_small.exists: false
                gshp_tech_heat_to_demand.exists: false

                chp_methane_back_pressure_simple_heat_storage_big.exists: false
                chp_methane_back_pressure_simple_tech_heat_to_demand.exists: false
                chp_methane_back_pressure_combined_heat_storage_big.exists: false
                chp_methane_back_pressure_combined_tech_heat_to_demand.exists: false

                hydrogen_electricity_storage.exists: false
                biogas_to_electricity_supply.exists: false # negating former bio-supply techs in EC2 & EC1
    no_bio_new:
        techs: 
            biomass_agr_1st_residue_supply.exists: false
            biomass_by_fats_supply.exists: false
            biomass_by_shell_supply.exists: false
            biomass_forest_supply.exists: false
            biomass_manure_supply.exists: false
            biomass_msw_supply.exists: false


            biofuel_to_diesel.exists: false
            biofuel_to_liquids.exists: false
            biofuel_to_methane.exists: false
            biofuel_to_methanol.exists: false
            biogas_to_methane.exists: false
            biogas_to_sng.exists: false
            biogas_engines.exists: false
            # cellulosic_to_ethanol.exists: false
            fats_uco_hydrogen_to_diesel.exists: false
            fats_uco_hydrogen_to_kerosene.exists: false
            fats_uco_to_diesel.exists: false
            manure_to_biogas.exists: false


            biofuel_boiler.exists: false
            biofuel_heat_storage_small.exists: false
            biofuel_tech_heat_to_demand.exists: false

            # chp_biofuel.exists: false # duplicated with config_overrides
            # chp_biofuel_heat_storage_big.exists: false
            # chp_biofuel_tech_heat_to_demand.exists: false

            chp_biofuel_extraction.exists: false
            chp_biofuel_extraction_heat_storage_big.exists: false
            chp_biofuel_extraction_tech_heat_to_demand.exists: false
            
            chp_wte_back_pressure.exists: false
            chp_wte_back_pressure_heat_storage_big.exists: false
            chp_wte_back_pressure_tech_heat_to_demand.exists: false
    